<?php

namespace App\Http\Ajax;

use App\Core\Ajax\AjaxHandler;
use App\Core\Request;
use WP_REST_Request;

class MainAjax extends AjaxHandler
{


    public function register($name)
    {
        parent::register($name); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $post = [
            'hello',
            'world'
        ];

        echo json_encode($post);
        die();
    }

    public function store(Request $request)
    {


        echo json_encode($request->all());
        echo json_encode(['post']);
        die();
    }

    public function show()
    {
        echo json_encode($_POST);
        die();
    }

    public function update()
    {
        echo json_encode($_POST);
        die();
    }

    public function destroy()
    {
        echo json_encode($_POST);
        die();
    }




}


