<?php

namespace App\Http\Ajax;

use App\Core\Ajax\AjaxHandler;

class MainAjax extends AjaxHandler {


    public function register($name)
    {
        parent::register($name); // TODO: Change the autogenerated stub
    }

    public function get()
    {

    }

    public function post()
    {

    }




}


