<?php

namespace App\Http\Ajax;

use App\Core\Ajax\AjaxHandler;

class MainAjax extends AjaxHandler {


    public function register($name)
    {
        parent::register($name); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $post = [
            'hello',
            'world'
        ];

        echo json_encode($post);
        die();
    }

    public function post()
    {

    }




}


